line-length = 110
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "ASYNC"]
ignore = ["E501", "B008"]

[lint.isort]
known-first-party = ["app"]

[format]
quote-style = "double"
indent-style = "space"
